import type { Agent, CatalogData, DriveDisc, Material, Team, Weapon } from '../schemas/catalog';

const agents: Agent[] = [
  {
    id: 'agent-ellen',
    slug: 'ellen-joe',
    name: '艾莲',
    name_en: 'Ellen Joe',
    rarity: 'S',
    element: 'Ice',
    role: 'Attack',
    faction: '维多利亚家政',
    avatar: 'https://placehold.co/96x96/0f172a/e2e8f0?text=%E8%89%BE%E8%8E%B2',
    cover: 'https://placehold.co/480x240/1e293b/e2e8f0?text=Ellen+Joe',
    summary: '冰属性站场主 C，擅长通过高速切入和连段打出持续爆发。',
    skill_intro: '依靠冲刺派生与强化普攻叠加节奏，在冰队中承担主要输出。',
    game_version: '1.0',
    released_at: '2024-07-04',
    updated_at: '2026-06-15',
    source_url: 'https://example.com/agents/ellen-joe',
  },
  {
    id: 'agent-zhu-yuan',
    slug: 'zhu-yuan',
    name: '朱鸢',
    name_en: 'Zhu Yuan',
    rarity: 'S',
    element: 'Ether',
    role: 'Attack',
    faction: '新艾利都治安局',
    avatar: 'https://placehold.co/96x96/0f172a/e2e8f0?text=%E6%9C%B1%E9%B8%A2',
    cover: 'https://placehold.co/480x240/172554/e2e8f0?text=Zhu+Yuan',
    summary: '以远程爆发和失衡追击见长的以太主 C。',
    skill_intro: '围绕强化霰弹与终结技打 burst，适合快速压血。',
    game_version: '1.0',
    released_at: '2024-08-14',
    updated_at: '2026-06-15',
    source_url: 'https://example.com/agents/zhu-yuan',
  },
  {
    id: 'agent-qingyi',
    slug: 'qingyi',
    name: '青衣',
    name_en: 'Qingyi',
    rarity: 'S',
    element: 'Electric',
    role: 'Stun',
    faction: '新艾利都治安局',
    avatar: 'https://placehold.co/96x96/0f172a/e2e8f0?text=%E9%9D%92%E8%A1%A3',
    cover: 'https://placehold.co/480x240/164e63/e2e8f0?text=Qingyi',
    summary: '高效率失衡角色，适合多种主 C 队伍作为通用拐点。',
    skill_intro: '通过高频电击与站场压制快速累积失衡值。',
    game_version: '1.1',
    released_at: '2024-09-04',
    updated_at: '2026-06-15',
    source_url: 'https://example.com/agents/qingyi',
  },
];

const weapons: Weapon[] = [
  {
    id: 'weapon-deep-sea-visitor',
    slug: 'deep-sea-visitor',
    name: '深海访客',
    rarity: 'S',
    image: 'https://placehold.co/360x360/0f172a/e2e8f0?text=%E6%B7%B1%E6%B5%B7%E8%AE%BF%E5%AE%A2',
    base_stat: '攻击力 713',
    sub_stat: '暴击率 24%',
    effect_desc: '提升冰属性伤害与冲刺攻击收益，适合艾莲等高频突进主 C。',
    fit_roles: ['Attack'],
    fit_agents: ['agent-ellen'],
    source_url: 'https://example.com/weapons/deep-sea-visitor',
    updated_at: '2026-06-15',
  },
  {
    id: 'weapon-riot-suppressor',
    slug: 'riot-suppressor-mark-vi',
    name: '防暴者 VI 型',
    rarity: 'S',
    image: 'https://placehold.co/360x360/172554/e2e8f0?text=%E9%98%B2%E6%9A%B4%E8%80%85',
    base_stat: '攻击力 713',
    sub_stat: '暴击伤害 48%',
    effect_desc: '强化远程爆发窗口，对朱鸢的 burst 周期非常契合。',
    fit_roles: ['Attack'],
    fit_agents: ['agent-zhu-yuan'],
    source_url: 'https://example.com/weapons/riot-suppressor-mark-vi',
    updated_at: '2026-06-15',
  },
  {
    id: 'weapon-teapot',
    slug: 'teapot',
    name: '玉壶青冰',
    rarity: 'S',
    image: 'https://placehold.co/360x360/164e63/e2e8f0?text=%E7%8E%89%E5%A3%B6%E9%9D%92%E5%86%B0',
    base_stat: '冲击力 18%',
    sub_stat: '攻击力 30%',
    effect_desc: '强化失衡施加效率，适合青衣这类站场失衡位。',
    fit_roles: ['Stun'],
    fit_agents: ['agent-qingyi'],
    source_url: 'https://example.com/weapons/teapot',
    updated_at: '2026-06-15',
  },
];

const driveDiscs: DriveDisc[] = [
  {
    id: 'drive-disc-polar-metal',
    slug: 'polar-metal',
    name: '极地重金属',
    two_piece_effect: '冰属性伤害提高 10%。',
    four_piece_effect: '攻击冰冻或失衡目标时，暴击伤害进一步提高。',
    fit_agents: ['agent-ellen'],
    fit_scenes: ['冰属性主 C', '短轴爆发'],
    updated_at: '2026-06-15',
  },
  {
    id: 'drive-disc-chaos-jazz',
    slug: 'chaos-jazz',
    name: '混沌爵士',
    two_piece_effect: '异常精通提高 30 点。',
    four_piece_effect: '离场后持续强化异常与追加伤害窗口。',
    fit_agents: ['agent-zhu-yuan'],
    fit_scenes: ['以太爆发', '速切输出'],
    updated_at: '2026-06-15',
  },
  {
    id: 'drive-disc-shockstar',
    slug: 'shockstar-disco',
    name: '震星迪斯科',
    two_piece_effect: '冲击力提高 6%。',
    four_piece_effect: '普攻、冲刺攻击对主目标造成的失衡值进一步提高。',
    fit_agents: ['agent-qingyi'],
    fit_scenes: ['失衡辅助', '前台控制'],
    updated_at: '2026-06-15',
  },
];

const teams: Team[] = [
  {
    id: 'team-ice-burst',
    slug: 'ellen-lycaon-soukaku',
    name: '艾莲冰爆发队',
    main_agent_id: 'agent-ellen',
    member_1_id: 'agent-qingyi',
    member_2_id: 'agent-zhu-yuan',
    backup_members: [],
    tags: ['爆发', '速通', '高练度'],
    summary: '利用失衡窗口和主 C 爆发段，在短时间内打满一轮输出。',
    rotation_tips: '先由失衡位压条，再切主 C 开爆发，最后补强终结技收尾。',
    strengths: ['爆发集中', '适合 boss 战'],
    weaknesses: ['对手法和轴要求较高'],
    updated_at: '2026-06-15',
  },
  {
    id: 'team-police-burst',
    slug: 'zhu-yuan-qingyi-nicole',
    name: '朱鸢治安局队',
    main_agent_id: 'agent-zhu-yuan',
    member_1_id: 'agent-qingyi',
    member_2_id: 'agent-ellen',
    backup_members: ['agent-ellen'],
    tags: ['以太', '失衡追击'],
    summary: '围绕朱鸢的强化弹夹与失衡爆发构建的标准输出队。',
    rotation_tips: '优先堆失衡，确保朱鸢在强化射击窗口内完成伤害倾泻。',
    strengths: ['成型快', '输出直观'],
    weaknesses: ['续航期伤害波动较大'],
    updated_at: '2026-06-15',
  },
];

const materials: Material[] = [
  {
    id: 'material-basic-freeze-chip',
    slug: 'basic-freeze-chip',
    name: '基础冰结芯片',
    type: '技能材料',
    icon: 'https://placehold.co/64x64/1d4ed8/e2e8f0?text=%E5%86%B0',
    source_desc: '实战模拟室、活动兑换、商店补给。',
    related_agents: ['agent-ellen'],
    updated_at: '2026-06-15',
  },
  {
    id: 'material-certified-seal',
    slug: 'certified-seal',
    name: '认证印章',
    type: '晋升材料',
    icon: 'https://placehold.co/64x64/7c3aed/e2e8f0?text=%E5%8D%B0',
    source_desc: '治安局委托、周常挑战、战令补给。',
    related_agents: ['agent-zhu-yuan', 'agent-qingyi'],
    updated_at: '2026-06-15',
  },
  {
    id: 'material-shock-chip',
    slug: 'advanced-shock-chip',
    name: '进阶电击芯片',
    type: '技能材料',
    icon: 'https://placehold.co/64x64/f59e0b/111827?text=%E7%94%B5',
    source_desc: '模拟训练、电系活动副本、材料精选。',
    related_agents: ['agent-qingyi'],
    updated_at: '2026-06-15',
  },
];

export const mockCatalogData: CatalogData = {
  agents,
  weapons,
  drive_discs: driveDiscs,
  teams,
  materials,
};
